### PR TITLE
Add new protocols tcp&, udp&, udp*& that enable SO_REUSEPORT

### PR DESCRIPTION
**Pull request by MarkRivers**
Add new protocols tcp&, udp&, udp*& that enable SO_REUSEPORT (or SO_REUSEADDR on Windows)

### CODE REVIEW

**Comment by MarkRivers** [comment]
This PR failed in Travis CI building on RTEMS.  SO_REUSEPORT appears to not be supported on RTEMS.

@norumwe12 do you know how we can handle this?  On Windows SO_REUSEADDR seems to work.  Would that also work on RTEMS?

**Comment by norumwe12** [comment]
My guess is that RTEMS is using a relatively old fork of the BSD network stack.

For now I think that just protecting the code in question with 
#ifdef SO_REUSEPORT
#endif
would be all that could be done.

**Comment by anjohnson** [comment]
Hey Eric, weren't you responsible for adding the RTEMS network stack in the first place? They are now finally replacing it in the 5.x series...

I haven't looked too closely but I'm pretty sure the Base sources have been using SO_REUSEADDR when SO_REUSEPORT is not available, so it might have been working on RTEMS. I think there has been some recent work in the 7.0 tree related to this but I haven't been following the details too closely. There may even be an API in osiSock.h to do this for you, but my recollection may be somewhat confused between what's happened on the 3.15 and 7.0 branches and that work might not have even been released yet, so you'll need to check (just to be aware what might happen in future Base releases).

**Comment by prjemian** [comment]
Ready to merge?

**Comment by prjemian** [comment]
CI [fails](https://travis-ci.org/github/epics-modules/asyn/jobs/677413207) on RTEMS for this change: 

    ../../asyn/drvAsynSerial/drvAsynIPPort.c:463: error: 'SO_REUSEPORT' undeclared (first use in this function)

**Comment by MarkRivers** [comment]
I have fixed the RTEMS build by using SO_REUSEADDR rather than SO_REUSEPORT, the same as on _WIN32.  It builds OK on Travis, but I don't have a way of testing if it actually works.

**Comment by prjemian** [comment]
Thanks!
